/**
 * Configuración visual de cada categoría del catálogo.
 * Modificar aquí para cambiar colores, iconos o descripciones.
 */
export const CATEGORY_ORDER = [
  "ALCOHOL",
  "REFRESCOS",
  "ZUMOS Y LACTEOS",
  "CERVEZAS Y MALTAS",
  "LEGUMBRES",
  "HARINAS",
  "CAFE Y TE",
  "CONDIMENTOS",
  "CONGELADOS",
  "HELADOS",
  "PULPAS",
  "REFRIGERADOS",
  "CONSERVAS",
  "GALLETAS",
  "GOLOSINAS",
  "PASTAS",
  "SNAKS",
  "VARIOS",
]

/**
 * Mapeo de nombres de familia del Excel → clave de categoría en el catálogo.
 * Permite normalizar variaciones tipográficas del Excel.
 */
export const EXCEL_FAMILY_MAP = {
  "ALCOHOLES":           "ALCOHOL",
  "REFRESCOS":           "REFRESCOS",
  "ZUMOS Y LACTEOS":     "ZUMOS Y LACTEOS",
  "MALTAS Y CERVEZAS":   "CERVEZAS Y MALTAS",
  "CERVEZAS Y MALTAS":   "CERVEZAS Y MALTAS",
  "LEGUMBRES":           "LEGUMBRES",
  "HARINAS":             "HARINAS",
  "CAFE Y TE":           "CAFE Y TE",
  "CONDIMENTOS":         "CONDIMENTOS",
  "CONGELADOS":          "CONGELADOS",
  "HELADOS":             "HELADOS",
  "PULPAS":              "PULPAS",
  "REFRIGERADOS":        "REFRIGERADOS",
  "CONSERVAS":           "CONSERVAS",
  "GALLETAS":            "GALLETAS",
  "GOLOSINAS":           "GOLOSINAS",
  "PASTAS":              "PASTAS",
  "SNAKS":               "SNAKS",
  "UTENSILIOS":          "VARIOS",
  "HIGIENE Y COSMETICA": "VARIOS",
}

export const CATEGORY_CONFIG = {
  ALCOHOL: {
    bg: "#1B2A6B",
    accent: "#4A6CF7",
    light: "#E8ECFF",
    icon: "🥃",
    subtitle: "Aguardientes · Rones · Licores",
    /** Imágenes usadas en la portada (mosaico) */
    coverImages: ["/images/82018.jpg", "/images/76002.jpg", "/images/IP98015.jpg"],
  },
  REFRESCOS: {
    bg: "#0A6B45",
    accent: "#22C55E",
    light: "#E8FFF4",
    icon: "🥤",
    subtitle: "Bebidas Refrescantes",
    coverImages: ["/images/63028.jpg", "/images/63037.jpg", "/images/63068.jpg"],
  },
  "ZUMOS Y LACTEOS": {
    bg: "#7A3A0A",
    accent: "#F97316",
    light: "#FFF7ED",
    icon: "🧃",
    subtitle: "Zumos Naturales · Leches Vegetales",
    coverImages: ["/images/69015.jpg", "/images/69021.jpg", "/images/69027.jpg"],
  },
  "CERVEZAS Y MALTAS": {
    bg: "#5C3A00",
    accent: "#EAB308",
    light: "#FEFCE8",
    icon: "🍺",
    subtitle: "Cervezas · Maltas",
    coverImages: ["/images/66003.jpg", "/images/66007.jpg", "/images/72004.jpg"],
  },
  LEGUMBRES: {
    bg: "#3B5E2B",
    accent: "#84CC16",
    light: "#F7FEE7",
    icon: "🫘",
    subtitle: "Legumbres · Granos",
    coverImages: [],
  },
  HARINAS: {
    bg: "#6B5B2A",
    accent: "#D97706",
    light: "#FFFBEB",
    icon: "🌾",
    subtitle: "Harinas · Cereales",
    coverImages: [],
  },
  "CAFE Y TE": {
    bg: "#3B1F0A",
    accent: "#92400E",
    light: "#FEF3C7",
    icon: "☕",
    subtitle: "Café · Té · Infusiones",
    coverImages: [],
  },
  CONDIMENTOS: {
    bg: "#7C1D1D",
    accent: "#EF4444",
    light: "#FEF2F2",
    icon: "🧂",
    subtitle: "Salsas · Especias · Aderezos",
    coverImages: [],
  },
  CONGELADOS: {
    bg: "#0C3654",
    accent: "#38BDF8",
    light: "#F0F9FF",
    icon: "🧊",
    subtitle: "Productos Congelados",
    coverImages: [],
  },
  HELADOS: {
    bg: "#5B1C6E",
    accent: "#C084FC",
    light: "#FAF5FF",
    icon: "🍦",
    subtitle: "Helados · Sorbetes",
    coverImages: [],
  },
  PULPAS: {
    bg: "#7C2D12",
    accent: "#FB923C",
    light: "#FFF7ED",
    icon: "🍊",
    subtitle: "Pulpas de Frutas",
    coverImages: [],
  },
  REFRIGERADOS: {
    bg: "#0F3D3D",
    accent: "#2DD4BF",
    light: "#F0FDFA",
    icon: "🧈",
    subtitle: "Productos Refrigerados",
    coverImages: [],
  },
  CONSERVAS: {
    bg: "#1E3A5F",
    accent: "#60A5FA",
    light: "#EFF6FF",
    icon: "🥫",
    subtitle: "Conservas · Enlatados",
    coverImages: [],
  },
  GALLETAS: {
    bg: "#6B3A1F",
    accent: "#FBBF24",
    light: "#FFFBEB",
    icon: "🍪",
    subtitle: "Galletas · Bizcochos",
    coverImages: [],
  },
  GOLOSINAS: {
    bg: "#6B1040",
    accent: "#F472B6",
    light: "#FDF2F8",
    icon: "🍬",
    subtitle: "Caramelos · Chucherías",
    coverImages: [],
  },
  PASTAS: {
    bg: "#5C4A00",
    accent: "#CA8A04",
    light: "#FEFCE8",
    icon: "🍝",
    subtitle: "Pastas · Arroces",
    coverImages: [],
  },
  SNAKS: {
    bg: "#2D1B69",
    accent: "#818CF8",
    light: "#EEF2FF",
    icon: "🍿",
    subtitle: "Snacks · Aperitivos",
    coverImages: [],
  },
  VARIOS: {
    bg: "#1F2937",
    accent: "#9CA3AF",
    light: "#F9FAFB",
    icon: "🧴",
    subtitle: "Utensilios · Higiene · Cosmética",
    coverImages: [],
  },
}

/** Imágenes del mosaico de portada (12 fotos, 4×3) */
export const COVER_MOSAIC = [
  "/images/82018.jpg",
  "/images/76002.jpg",
  "/images/63028.jpg",
  "/images/66003.jpg",
  "/images/69015.jpg",
  "/images/82010.jpg",
  "/images/63037.jpg",
  "/images/69021.jpg",
  "/images/76022.jpg",
  "/images/63068.jpg",
  "/images/IP66005.jpg",
  "/images/72004.jpg",
]

/** Datos de contacto de la empresa */
export const COMPANY = {
  name: "IMPORMED",
  tagline: "Productos Internacionales",
  phone: "961 250 501",
  email: "pedidos@impormed.com",
  web: "www.impormed.com",
  minOrder: "50€",
  hours: "Lunes a Viernes · 9h a 18.30h",
}
