create table public.catalog_categories (
  id bigint generated by default as identity primary key,
  code text not null unique,
  source_name text not null unique,
  display_name text not null,
  sort_order integer not null default 0,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

insert into public.catalog_categories (code, source_name, display_name, sort_order) values
  ('alcohol', 'ALCOHOLES', 'ALCOHOL', 10),
  ('refrescos-maltas-cervezas', 'REFRESCOS, MALTAS Y CERVEZAS', 'REFRESCOS, MALTAS Y CERVEZAS', 20),
  ('zumos-lacteos', 'ZUMOS Y LACTEOS', 'ZUMOS Y LACTEOS', 30),
  ('legumbres', 'LEGUMBRES', 'LEGUMBRES', 40),
  ('harinas-pastas', 'HARINAS Y PASTAS', 'HARINAS Y PASTAS', 50),
  ('cafe-te', 'CAFE Y TE', 'CAFE Y TE', 60),
  ('condimentos', 'CONDIMENTOS', 'CONDIMENTOS', 70),
  ('congelados', 'CONGELADOS', 'CONGELADOS', 80),
  ('helados', 'HELADOS', 'HELADOS', 90),
  ('pulpas', 'PULPAS', 'PULPAS', 100),
  ('refrigerados', 'REFRIGERADOS', 'REFRIGERADOS', 110),
  ('conservas', 'CONSERVAS', 'CONSERVAS', 120),
  ('galletas', 'GALLETAS', 'GALLETAS', 130),
  ('golosinas', 'GOLOSINAS', 'GOLOSINAS', 140),
  ('snaks', 'SNAKS', 'SNAKS', 150),
  ('varios', 'VARIOS', 'VARIOS', 160);

create table public.catalogs (
  id uuid primary key default gen_random_uuid(),
  slug text not null unique,
  name text not null,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

insert into public.catalogs (slug, name)
values ('catalogo-principal', 'Catálogo principal');

alter table public.products
  add column display_name text,
  add column stock_units numeric(12,3),
  add column units_per_case integer,
  add column category_id bigint references public.catalog_categories(id);

update public.products p
set display_name = coalesce(cp.display_name, p.article_name),
    units_per_case = case
      when cp.units_label ~ '^\s*\d+' then
        (substring(cp.units_label from '^\s*(\d+)'))::integer
      else null
    end,
    category_id = c.id
from public.catalog_products cp,
     public.catalog_categories c
where cp.product_id = p.id
  and c.display_name = cp.category;

alter table public.products
  alter column display_name set not null,
  alter column category_id set not null;

alter table public.catalog_products
  add column catalog_id uuid references public.catalogs(id);

update public.catalog_products
set catalog_id = (
  select id from public.catalogs where slug = 'catalogo-principal'
);

alter table public.catalog_products
  alter column catalog_id set not null;

alter table public.catalog_products drop constraint catalog_products_pkey;
alter table public.catalog_products add primary key (catalog_id, product_id);

alter table public.catalog_products
  drop column display_name,
  drop column units_label,
  drop column category;

alter table public.products
  drop column units,
  drop column family_name;

create index products_category_id_idx
  on public.products (category_id);

create index catalog_products_product_id_idx
  on public.catalog_products (product_id);

create index catalog_products_catalog_sort_order_idx
  on public.catalog_products (catalog_id, sort_order);

alter table public.catalog_categories enable row level security;
alter table public.catalogs enable row level security;

create policy "catalog categories are publicly readable"
  on public.catalog_categories for select
  to anon, authenticated
  using (active = true);

create policy "active catalogs are publicly readable"
  on public.catalogs for select
  to anon, authenticated
  using (active = true);

create policy "catalog admins manage categories"
  on public.catalog_categories for all
  to authenticated
  using (
    exists (
      select 1 from public.catalog_admins
      where user_id = auth.uid()
    )
  )
  with check (
    exists (
      select 1 from public.catalog_admins
      where user_id = auth.uid()
    )
  );

create policy "catalog admins manage catalogs"
  on public.catalogs for all
  to authenticated
  using (
    exists (
      select 1 from public.catalog_admins
      where user_id = auth.uid()
    )
  )
  with check (
    exists (
      select 1 from public.catalog_admins
      where user_id = auth.uid()
    )
  );
